### PR TITLE
fix: #808 Payment referenceType NULL due to bad migration

### LINKED ISSUE #808: Payments not showing up
https://github.com/frappe/books/assets/29507195/7a1aedbb-a984-44c7-88ac-9fd852f3d5ea

Payments don't show up in the List view when navigating to using the sidebar. Individual payments can be viewed when navigating to using Invoice links.

### PR DESCRIPTION
**Pull request by mildred**
Fix #808

### CODE REVIEW

**Comment by Isaac-GC** [comment]
~~LGTM!~~

A good point was raised here: https://github.com/frappe/books/issues/808#issuecomment-1895632861

Taking a second look jic

**Review by Isaac-GC — APPROVED** [review]

File: backend/patches/setPaymentReferenceType.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import { DatabaseManager } from '../database/manager';
+
+async function execute(dm: DatabaseManager) {
+  await dm.db!.knex!('Payment')
+    .where({ referenceType: null })
+    .update({ referenceType: 'SalesInvoice' });
```
Comment (Isaac-GC) [inline backend/patches/setPaymentReferenceType.ts]: Can you update this to the following please?
```ts
  await dm.db!.knex!('Payment')
    .where({ referenceType: null })
    .andWhere({ paymentType: 'Receive' })
    .update({ referenceType: 'SalesInvoice' });

  await dm.db!.knex!('Payment')
    .where({ referenceType: null })
    .andWhere({ paymentType: 'Pay' })
    .update({ referenceType: 'PurchaseInvoice' });
```

File: backend/patches/index.ts [hunk 2]
```diff
@@ -28,4 +29,9 @@ export default [
     version: '0.6.6-beta.0',
     patch: createInventoryNumberSeries,
   },
+  {
+    name: 'setPaymentReferenceType',
+    version: '0.21.0',
```
Comment (Isaac-GC) [inline backend/patches/index.ts:34]: Let's change  the version code to `0.20.1` for the minor/bug update.

**Comment by Isaac-GC** [comment]
Hi @mildred, 

The patch was looking to be marking both types, sales and payment, as SalesInvoice's. Please see the above code in the review that should fix both types of invoices. 

If also possible, could I please have you update/add the package.json with version code `0.20.1`?

**Review by Isaac-GC — APPROVED** [review]
